# X-tee portaalide PostgreSQL andmestruktuur

prefix=/usr/xtee

DESTDIR = 

all: 
	mkdir -p $(DESTDIR)$(prefix)/orbeon
	cp install-* $(DESTDIR)$(prefix)/orbeon
	cp war/* $(DESTDIR)$(prefix)/orbeon/
	cp conf/* $(DESTDIR)$(prefix)/orbeon/
