# X-tee portaalide PostgreSQL andmestruktuur

prefix=/usr/xtee

DESTDIR = 

all: 
	mkdir -p $(DESTDIR)$(prefix)/db/install
	mkdir -p $(DESTDIR)$(prefix)/db/sql
	cp install-* $(DESTDIR)$(prefix)/db/install/
	cp db/sql/* $(DESTDIR)$(prefix)/db/sql/

