# X-tee portaalide base paketti struktuur

prefix=/usr/xtee

DESTDIR = 

all: 
	mkdir -p $(DESTDIR)$(prefix)/apache2
	cp install-* $(DESTDIR)$(prefix)/apache2
	cp conf/* $(DESTDIR)$(prefix)/apache2
	cp util/* $(DESTDIR)$(prefix)/apache2

