# X-tee5 MISP2 rakenduse install

prefix=/usr/xtee

DESTDIR = 

all: 
	mkdir -p $(DESTDIR)$(prefix)/app
	cp install-* $(DESTDIR)$(prefix)/app/
	cp war/* $(DESTDIR)$(prefix)/app/
	cp conf/* $(DESTDIR)$(prefix)/app/
	cp util/* $(DESTDIR)$(prefix)/app/
