#!/bin/bash -e

set -e
#set -xv
# Source debconf library.
if [[  -e /usr/share/debconf/confmodule ]] ; then 
. /usr/share/debconf/confmodule
fi

apache2_home=/etc/apache2

config_operation="$1"

if [ "$config_operation" == "configure" ] || [ "$config_operation" == "reconfigure" ]; then
    if [ -f $apache2_home/sites-available/ssl.conf ]; then
        db_set xtee-misp2-base/apache_ssl_config_exists true
        db_input medium xtee-misp2-base/apache2_overwrite_confirmation || true
    fi
    db_input medium  shared/xtee-misp2/international_installation_requested || true
    # shellcheck disable=SC2119 # no parameter is intended to be passed
    db_go  || true
fi
db_stop
