
- name: Ready all Ubuntu {{ubuntu_releasever}} containers
  with_inventory_hostnames: all:!lxd-servers
  lxd_container:
    name: "{{item}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: ubuntu/{{ubuntu_releasever}}/amd64
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  tags:
    - ubuntu-container-init

- name: Check if Python2 is installed in {{ubuntu_releasever}} containers
  with_inventory_hostnames: all:!lxd-servers:!centos-ss
  delegate_to: "{{item}}"
  raw: dpkg -s python
  register: python_check_is_installed
  failed_when: python_check_is_installed.rc not in [0,1]
  changed_when: false

- name: Install Python2 in container
  delegate_to: "{{item.item}}"
  raw: apt-get update && apt-get install -y python
  when: item.rc == 1
  with_items:
    - "{{python_check_is_installed.results}}"
